[package]
name = "harvester_core"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
url = "2"
harvester_engine = { path = "../harvester_engine" }
chrono = "0.4"
engine_logging = { path = "../engine_logging" }
sha2 = "0.11.0"
log.workspace = true
serde = { version = "1", features = ["derive"] }
